billing-service:
  transport:
    topics:
      account:
        create: ${ACCOUNT_CREATE_TOPIC:create}
      order:
        request: ${ORDER_REQUEST_TOPIC:request}
        response: ${ORDER_RESPONSE_TOPIC:response}

spring:
  kafka:
    consumer:
      client-id: ${KAFKA_CLIENT_ID:billing-service}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: billing-service-group
      auto-offset-reset: earliest
      security.protocol: ${KAFKA_PROTOCOL:PLAINTEXT}
    producer:
      client-id: ${KAFKA_CLIENT_ID:billing-service}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      acks: all
      security.protocol: ${KAFKA_PROTOCOL:PLAINTEXT}
  profiles:
    active: ${SPRING_PROFILE:prod}
logging:
  level:
    org.apache.kafka.*: WARN

server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping.health: health
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true